import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/context/theme-provider';
import { ModeToggle } from '@/components/modeToggle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Military Service Countdown',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="text-center pt-6">
            <ModeToggle />
          </div>
          {children}
          {/* add footer that contain my name "a7mdmo74" & link to my github repo */}
          <footer className="text-center mt-8">
            <p>
              Made by{' '}
              <a
                href="https://github.com/a7mdmo74"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500"
              >
                a7mdmo74
              </a>
            </p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
